#Basic Python Alpine image
FROM python:3.12-alpine

# Set the running directory
WORKDIR /app

# Python requirements file
COPY requirements.txt .

# Install requirement dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Secret arguments
ARG INFLUXDB_URL
ARG INFLUXDB_TOKEN
ARG INFLUXDB_ORG
ARG INFLUXDB_BUCKET
ARG MQTT_USERNAME
ARG MQTT_PASSWORD
ARG MQTT_BROKER
ARG MQTT_PORT
ARG MQTT_TOPIC
ARG VOLTAGE_OFF_THRESHOLD
ARG VOLTAGE_ON_THRESHOLD

# Set environment variables
ENV INFLUXDB_URL=$INFLUXDB_URL
ENV INFLUXDB_TOKEN=$INFLUXDB_TOKEN  
ENV INFLUXDB_ORG=$INFLUXDB_ORG
ENV INFLUXDB_BUCKET=$INFLUXDB_BUCKET
ENV MQTT_USERNAME=$MQTT_USERNAME
ENV MQTT_PASSWORD=$MQTT_PASSWORD
ENV MQTT_BROKER=$MQTT_BROKER
ENV MQTT_PORT=$MQTT_PORT
ENV MQTT_TOPIC=$MQTT_TOPIC
ENV VOLTAGE_OFF_THRESHOLD=$VOLTAGE_OFF_THRESHOLD
ENV VOLTAGE_ON_THRESHOLD=$VOLTAGE_ON_THRESHOLD

# Copy python folder
COPY python/ .

# Set the default command to run a Python script (change "app.py" as needed)
CMD ["python", "power-monitor.py"]
