name: esp32-pc-power-controller 

on:
  push:
    branches: [ "dev", "main"]
  pull_request:
    branches: [ "dev", "main"]
  
jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        TIMESTAMP=$(date +%s)
        echo ${{ secrets.REPO_TOKEN }} | docker login --username ${{ github.repository_owner}} --password-stdin ghcr.io
        docker build . --file Dockerfile --tag esp32-pc-power-controller:$TIMESTAMP
        
    - name: push to repo
      run: |
        docker tag esp32-pc-power-controller:$TIMESTAMP ghcr.io/${{ github.repository_owner}}/esp32-pc-power-controller:$TIMESTAMP
        docker tag esp32-pc-power-controller:$TIMESTAMP ghcr.io/${{ github.repository_owner}}/esp32-pc-power-controller:latest
        docker push ghcr.io/${{ github.repository_owner}}/esp32-pc-power-controller:$TIMESTAMP
        docker push ghcr.io/${{ github.repository_owner}}/esp32-pc-power-controller:latest
